let storedWords = JSON.parse(localStorage.getItem("words"));

if (storedWords === null || storedWords.length < 1) {
  var defaultWords = [
    ["the", "o"],
    ["be", "olmak"],
    ["and", "ve"],
    ["of", "ın"],
    ["a", "bir"],
    ["in", "içinde"],
    ["to", "gitmek"],
    ["have", "sahip olmak"],
    ["it", "o"],
    ["I", "ben"],
    ["that", "şu"],
    ["for", "için"],
    ["you", "sen"],
    ["he", "o"],
    ["with", "ile"],
    ["on", "üzerinde"],
    ["do", "yapmak"],
    ["say", "demek"],
    ["this", "bu"],
    ["they", "onlar"],
    ["at", "de"],
    ["but", "ama"],
    ["we", "biz"],
    ["his", "onun"],
    ["from", "den"],
    ["not", "değil"],
    ["by", "tarafından"],
    ["she", "o"],
    ["or", "veya"],
    ["as", "olarak"],
    ["what", "ne"],
    ["go", "gitmek"],
    ["their", "onların"],
    ["can", "yapabilmek"],
    ["who", "kim"],
    ["get", "almak"],
    ["if", "eğer"],
    ["would", "olur"],
    ["her", "onun"],
    ["all", "tüm"],
    ["my", "benim"],
    ["make", "yapmak"],
    ["about", "hakkında"],
    ["know", "bilmek"],
    ["will", "olacak"],
    ["up", "yukarı"],
    ["one", "bir"],
    ["time", "zaman"],
    ["there", "orada"],
    ["year", "yıl"],
    ["so", "bu yüzden"],
    ["think", "düşünmek"],
    ["when", "ne zaman"],
    ["which", "hangi"],
    ["them", "onları"],
    ["some", "bazı"],
    ["me", "beni"],
    ["people", "insanlar"],
    ["take", "almak"],
    ["out", "dışarı"],
    ["into", "içine"],
    ["just", "sadece"],
    ["see", "görmek"],
    ["him", "onu"],
    ["your", "senin"],
    ["come", "gelmek"],
    ["could", "olabilir"],
    ["now", "şimdi"],
    ["than", "daha"],
    ["like", "gibi"],
    ["other", "diğer"],
    ["how", "nasıl"],
    ["then", "daha sonra"],
    ["its", "onun"],
    ["our", "bizim"],
    ["two", "iki"],
    ["more", "daha fazla"],
    ["these", "bunlar"],
    ["want", "istemek"],
    ["way", "yol"],
    ["look", "bakmak"],
    ["first", "ilk"],
    ["also", "ayrıca"],
    ["new", "yeni"],
    ["because", "çünkü"],
    ["day", "gün"],
    ["more", "daha fazla"],
    ["use", "kullanmak"],
    ["no", "hayır"],
    ["man", "adam"],
    ["find", "bulmak"],
    ["here", "burada"],
    ["thing", "şey"],
    ["give", "vermek"],
    ["many", "çok"],
    ["well", "iyi"],
    ["only", "sadece"],
    ["those", "onlar"],
    ["tell", "söylemek"],
    ["very", "çok"],
    ["even", "bile"],
    ["back", "geri"],
    ["any", "herhangi"],
    ["good", "iyi"],
    ["woman", "kadın"],
    ["through", "arasından"],
    ["us", "bizi"],
    ["life", "hayat"],
    ["child", "çocuk"],
    ["work", "çalışmak"],
    ["down", "aşağı"],
    ["may", "olabilir"],
    ["after", "sonra"],
    ["should", "yapmalı"],
    ["call", "aramak"],
    ["world", "dünya"],
    ["over", "üzerinde"],
    ["school", "okul"],
    ["still", "hala"],
    ["try", "denemek"],
    ["in", "içinde"],
    ["as", "olarak"],
    ["last", "son"],
    ["ask", "sormak"],
    ["need", "ihtiyaç"],
    ["too", "de"],
    ["feel", "hissetmek"],
    ["three", "üç"],
    ["when", "ne zaman"],
    ["state", "devlet"],
    ["never", "hiçbir zaman"],
    ["become", "olmak"],
    ["between", "arasında"],
    ["high", "yüksek"],
    ["really", "gerçekten"],
    ["something", "bir şey"],
    ["most", "en çok"],
    ["another", "başka"],
    ["much", "çok"],
    ["family", "aile"],
    ["own", "kendi"],
    ["out", "dışarı"],
    ["leave", "ayrılmak"],
    ["put", "koymak"],
    ["old", "eski"],
    ["while", "iken"],
    ["mean", "anlamına gelmek"],
    ["on", "üzerinde"],
    ["keep", "saklamak"],
    ["student", "öğrenci"],
    ["why", "neden"],
    ["let", "izin vermek"],
    ["great", "harika"],
    ["same", "aynı"],
    ["big", "büyük"],
    ["group", "grup"],
    ["begin", "başlamak"],
    ["seem", "görünmek"],
    ["country", "ülke"],
    ["help", "yardım etmek"],
    ["talk", "konuşmak"],
    ["where", "nerede"],
    ["turn", "dönmek"],
    ["problem", "sorun"],
    ["every", "her"],
    ["start", "başlamak"],
    ["hand", "el"],
    ["might", "olabilir"],
    ["American", "Amerikalı"],
    ["show", "göstermek"],
    ["part", "bölüm"],
    ["about", "hakkında"],
    ["against", "karşı"],
    ["place", "yer"],
    ["over", "üzerinde"],
    ["such", "böyle"],
    ["again", "tekrar"],
    ["few", "birkaç"],
    ["case", "durum"],
    ["most", "çoğu"],
    ["week", "hafta"],
    ["company", "şirket"],
    ["where", "nerede"],
    ["system", "sistem"],
    ["each", "her biri"],
    ["right", "doğru"],
    ["program", "program"],
    ["hear", "duymak"],
    ["so", "bu yüzden"],
    ["question", "soru"],
    ["during", "sırasında"],
    ["work", "iş"],
    ["play", "oynamak"],
    ["government", "hükümet"],
    ["run", "koşmak"],
    ["small", "küçük"],
    ["number", "numara"],
    ["off", "kapalı"],
    ["always", "her zaman"],
    ["move", "hareket etmek"],
    ["like", "gibi"],
    ["night", "gece"],
    ["live", "yaşamak"],
    ["Mr.", "Bay"],
    ["point", "nokta"],
    ["home", "ev"],
    ["believe", "inanmak"],
    ["hold", "tutmak"],
    ["today", "bugün"],
    ["bring", "getirmek"],
    ["happen", "olmak"],
    ["next", "sonraki"],
    ["without", "olmadan"],
    ["before", "önce"],
    ["large", "büyük"],
    ["all", "hepsi"],
    ["million", "milyon"],
    ["must", "gerek"],
    ["under", "altında"],
    ["water", "su"],
    ["room", "oda"],
    ["write", "yazmak"],
    ["mother", "anne"],
    ["area", "alan"],
    ["national", "ulusal"],
    ["money", "para"],
    ["story", "hikaye"],
    ["young", "genç"],
    ["fact", "gerçek"],
    ["month", "ay"],
    ["different", "farklı"],
    ["lot", "çok"],
    ["right", "hak"],
    ["study", "çalışmak"],
    ["book", "kitap"],
    ["eye", "göz"],
    ["job", "iş"],
    ["word", "kelime"],
    ["though", "rağmen"],
    ["business", "iş"],
    ["issue", "sorun"],
    ["side", "yan"],
    ["kind", "tür"],
    ["four", "dört"],
    ["head", "baş"],
    ["far", "uzak"],
    ["black", "siyah"],
    ["long", "uzun"],
    ["both", "her ikisi de"],
    ["little", "az"],
    ["house", "ev"],
    ["yes", "evet"],
    ["after", "sonra"],
    ["since", "beri"],
    ["long", "uzun"],
    ["provide", "sağlamak"],
    ["service", "hizmet"],
    ["around", "etrafında"],
    ["friend", "arkadaş"],
    ["important", "önemli"],
    ["father", "baba"],
    ["sit", "oturmak"],
    ["away", "uzakta"],
    ["until", "kadar"],
    ["power", "güç"],
    ["hour", "saat"],
    ["game", "oyun"],
    ["often", "sık sık"],
    ["yet", "henüz"],
    ["line", "hat"],
    ["political", "siyasi"],
    ["end", "son"],
    ["among", "arasında"],
    ["ever", "hiç"],
    ["stand", "dikmek"],
    ["bad", "kötü"],
    ["lose", "kaybetmek"],
    ["however", "ancak"],
    ["member", "üye"],
    ["pay", "ödemek"],
    ["law", "hukuk"],
    ["meet", "tanışmak"],
    ["car", "araba"],
    ["city", "şehir"],
    ["almost", "neredeyse"],
    ["include", "dahil etmek"],
    ["continue", "devam etmek"],
    ["set", "ayarlamak"],
    ["later", "daha sonra"],
    ["community", "toplum"],
    ["name", "isim"],
    ["five", "beş"],
    ["once", "bir kez"],
    ["white", "beyaz"],
    ["least", "en az"],
    ["president", "başkan"],
    ["learn", "öğrenmek"],
    ["real", "gerçek"],
    ["change", "değişmek"],
    ["team", "takım"],
    ["minute", "dakika"],
    ["best", "en iyi"],
    ["several", "birçok"],
    ["idea", "fikir"],
    ["kid", "çocuk"],
    ["body", "vücut"],
    ["information", "bilgi"],
    ["nothing", "hiçbir şey"],
    ["ago", "önce"],
    ["right", "sağ"],
    ["lead", "yönetmek"],
    ["social", "sosyal"],
    ["understand", "anlamak"],
    ["whether", "olup olmadığı"],
    ["watch", "izlemek"],
    ["together", "birlikte"],
    ["follow", "takip etmek"],
    ["parent", "ebeveyn"],
    ["stop", "durdurmak"],
    ["face", "yüz"],
    ["anything", "herhangi bir şey"],
    ["create", "oluşturmak"],
    ["public", "genel"],
    ["already", "zaten"],
    ["speak", "konuşmak"],
    ["others", "diğerleri"],
    ["read", "okumak"],
    ["level", "seviye"],
    ["allow", "izin vermek"],
    ["add", "eklemek"],
    ["office", "ofis"],
    ["spend", "harcamak"],
    ["door", "kapı"],
    ["health", "sağlık"],
    ["person", "kişi"],
    ["art", "sanat"],
    ["sure", "emin"],
    ["such", "böyle"],
    ["war", "savaş"],
    ["history", "tarih"],
    ["party", "parti"],
    ["within", "içinde"],
    ["grow", "büyümek"],
    ["result", "sonuç"],
    ["open", "açık"],
    ["change", "değişim"],
    ["morning", "sabah"],
    ["walk", "yürümek"],
    ["reason", "neden"],
    ["low", "düşük"],
    ["win", "kazanmak"],
    ["research", "araştırma"],
    ["girl", "kız"],
    ["guy", "adam"],
    ["early", "erken"],
    ["food", "yemek"],
    ["before", "önce"],
    ["moment", "an"],
    ["himself", "kendisi"],
    ["air", "hava"],
    ["teacher", "öğretmen"],
    ["force", "güç"],
    ["offer", "teklif"],
    ["enough", "yeterli"],
    ["both", "her ikisi"],
    ["education", "eğitim"],
    ["across", "karşısında"],
    ["although", "rağmen"],
    ["remember", "hatırlamak"],
    ["foot", "ayak"],
    ["second", "ikinci"],
    ["boy", "erkek çocuk"],
    ["maybe", "belki"],
    ["toward", "doğru"],
    ["able", "yetenekli"],
    ["age", "yaş"],
    ["policy", "politika"],
    ["everything", "her şey"],
    ["love", "aşk"],
    ["process", "süreç"],
    ["music", "müzik"],
    ["including", "dahil olmak üzere"],
    ["consider", "düşünmek"],
    ["appear", "görünmek"],
    ["actually", "aslında"],
    ["buy", "satın almak"],
    ["probably", "muhtemelen"],
    ["human", "insan"],
    ["wait", "beklemek"],
    ["serve", "hizmet etmek"],
    ["market", "pazar"],
    ["die", "ölmek"],
    ["send", "göndermek"],
    ["expect", "beklemek"],
    ["home", "ev"],
    ["sense", "anlam"],
    ["build", "inşa etmek"],
    ["stay", "kalmak"],
    ["fall", "düşmek"],
    ["reach", "ulaşmak"],
    ["local", "yerel"],
    ["kill", "öldürmek"],
    ["six", "altı"],
    ["remain", "kalmak"],
    ["effect", "etki"],
    ["use", "kullanmak"],
    ["yeah", "evet"],
    ["suggest", "önermek"],
    ["class", "sınıf"],
    ["control", "kontrol"],
    ["raise", "artırmak"],
    ["care", "ilgilenmek"],
    ["perhaps", "belki"],
    ["little", "küçük"],
    ["late", "geç"],
    ["hard", "zor"],
    ["field", "alan"],
    ["else", "başka"],
    ["pass", "geçmek"],
    ["former", "eski"],
    ["sell", "satmak"],
    ["major", "büyük"],
    ["sometimes", "bazen"],
    ["require", "gerektirmek"],
    ["along", "boyunca"],
    ["development", "gelişim"],
    ["themselves", "kendileri"],
    ["report", "rapor"],
    ["role", "rol"],
    ["better", "daha iyi"],
    ["economic", "ekonomik"],
    ["effort", "çaba"],
    ["decide", "karar vermek"],
    ["rate", "oran"],
    ["strong", "güçlü"],
    ["possible", "mümkün"],
    ["heart", "kalp"],
    ["drug", "ilaç"],
    ["show", "göstermek"],
    ["leader", "lider"],
    ["light", "ışık"],
    ["voice", "ses"],
    ["wife", "eş"],
    ["whole", "tüm"],
    ["police", "polis"],
    ["mind", "akıl"],
    ["finally", "sonunda"],
    ["pull", "çekmek"],
    ["return", "geri dönmek"],
    ["free", "özgür"],
    ["military", "askeri"],
    ["price", "fiyat"],
    ["report", "bildiri"],
    ["less", "daha az"],
    ["according", "göre"],
    ["decision", "karar"],
    ["explain", "açıklamak"],
    ["son", "oğul"],
    ["hope", "umut"],
    ["even", "hatta"],
    ["develop", "geliştirmek"],
    ["view", "görünüm"],
    ["relationship", "ilişki"],
    ["carry", "taşımak"],
    ["town", "kasaba"],
    ["road", "yol"],
    ["drive", "sürmek"],
    ["arm", "kol"],
    ["true", "doğru"],
    ["federal", "federal"],
    ["break", "kırmak"],
    ["better", "daha iyi"],
    ["difference", "fark"],
    ["thank", "teşekkür etmek"],
    ["receive", "almak"],
    ["value", "değer"],
    ["international", "uluslararası"],
    ["building", "bina"],
    ["action", "eylem"],
    ["full", "tam"],
    ["model", "model"],
    ["join", "katılmak"],
    ["season", "mevsim"],
    ["society", "toplum"],
    ["because", "çünkü"],
    ["tax", "vergi"],
    ["director", "yönetmen"],
    ["early", "erken"],
    ["position", "pozisyon"],
    ["player", "oyuncu"],
    ["agree", "katılmak"],
    ["especially", "özellikle"],
    ["record", "kayıt"],
    ["pick", "seçmek"],
    ["wear", "giymek"],
    ["paper", "kağıt"],
    ["special", "özel"],
    ["space", "uzay"],
    ["ground", "yer"],
    ["form", "form"],
    ["support", "destek"],
    ["event", "olay"],
    ["official", "resmi"],
    ["whose", "kimin"],
    ["matter", "önemli"],
    ["everyone", "herkes"],
    ["center", "merkez"],
    ["couple", "çift"],
    ["site", "site"],
    ["end", "son"],
    ["project", "proje"],
    ["hit", "vurmak"],
    ["base", "temel"],
    ["activity", "etkinlik"],
    ["star", "yıldız"],
    ["table", "masa"],
    ["need", "ihtiyaç"],
    ["court", "mahkeme"],
    ["produce", "üretmek"],
    ["eat", "yemek"],
    ["teach", "öğretmek"],
    ["oil", "yağ"],
    ["half", "yarım"],
    ["situation", "durum"],
    ["easy", "kolay"],
    ["cost", "maliyet"],
    ["industry", "sanayi"],
    ["figure", "şekil"],
    ["face", "yüzleşmek"],
    ["street", "sokak"],
    ["image", "görüntü"],
    ["itself", "kendi kendine"],
    ["phone", "telefon"],
    ["either", "ya"],
    ["data", "veri"],
    ["cover", "örtmek"],
    ["quite", "oldukça"],
    ["picture", "resim"],
    ["clear", "açık"],
    ["practice", "uygulama"],
    ["piece", "parça"],
    ["land", "toprak"],
    ["recent", "son"],
    ["describe", "tanımlamak"],
    ["product", "ürün"],
    ["doctor", "doktor"],
    ["wall", "duvar"],
    ["patient", "hasta"],
    ["worker", "işçi"],
    ["news", "haberler"],
    ["test", "test"],
    ["movie", "film"],
    ["certain", "belirli"],
    ["north", "kuzey"],
    ["love", "sevgi"],
    ["personal", "kişisel"],
    ["open", "açmak"],
    ["support", "desteklemek"],
    ["simply", "basitçe"],
    ["third", "üçüncü"],
    ["technology", "teknoloji"],
    ["catch", "yakalamak"],
    ["step", "adım"],
    ["baby", "bebek"],
    ["computer", "bilgisayar"],
    ["type", "tür"],
    ["attention", "dikkat"],
    ["draw", "çizmek"],
    ["film", "film"],
    ["Republican", "Cumhuriyetçi"],
    ["tree", "ağaç"],
    ["source", "kaynak"],
    ["red", "kırmızı"],
    ["nearly", "neredeyse"],
    ["organization", "kuruluş"],
    ["choose", "seçmek"],
    ["cause", "neden olmak"],
    ["hair", "saç"],
    ["century", "yüzyıl"],
    ["evidence", "kanıt"],
    ["window", "pencere"],
    ["difficult", "zor"],
    ["listen", "dinlemek"],
    ["soon", "yakında"],
    ["culture", "kültür"],
    ["billion", "milyar"],
    ["chance", "şans"],
    ["brother", "erkek kardeş"],
    ["energy", "enerji"],
    ["period", "dönem"],
    ["summer", "yaz"],
    ["realize", "farkına varmak"],
    ["hundred", "yüz"],
    ["available", "müsait"],
    ["plant", "bitki"],
    ["likely", "olası"],
    ["opportunity", "fırsat"],
    ["term", "dönem"],
    ["short", "kısa"],
    ["letter", "mektup"],
    ["condition", "durum"],
    ["choice", "seçim"],
    ["place", "yer"],
    ["single", "tek"],
    ["rule", "kural"],
    ["daughter", "kız çocuk"],
    ["administration", "yönetim"],
    ["south", "güney"],
    ["husband", "eş"],
    ["Congress", "Kongre"],
    ["floor", "zemin"],
    ["campaign", "kampanya"],
    ["material", "malzeme"],
    ["population", "nüfus"],
    ["well", "iyi"],
    ["call", "çağrı"],
    ["economy", "ekonomi"],
    ["medical", "tıbbi"],
    ["hospital", "hastane"],
    ["church", "kilise"],
    ["close", "kapatmak"],
    ["thousand", "bin"],
    ["risk", "risk"],
    ["current", "şu anki"],
    ["fire", "ateş"],
    ["future", "gelecek"],
    ["wrong", "yanlış"],
    ["involve", "dahil etmek"],
    ["defense", "savunma"],
    ["anyone", "herhangi biri"],
    ["increase", "artmak"],
    ["security", "güvenlik"],
    ["bank", "banka"],
    ["myself", "kendim"],
    ["certainly", "kesinlikle"],
    ["west", "batı"],
    ["sport", "spor"],
    ["board", "tahta"],
    ["seek", "araştırmak"],
    ["per", "başına"],
    ["subject", "konu"],
    ["officer", "memur"],
    ["private", "özel"],
    ["rest", "dinlenmek"],
    ["behavior", "davranış"],
    ["deal", "anlaşma"],
    ["performance", "performans"],
    ["fight", "dövüşmek"],
    ["throw", "atmak"],
    ["top", "üst"],
    ["quickly", "hızlı bir şekilde"],
    ["past", "geçmiş"],
    ["goal", "hedef"],
    ["bed", "yatak"],
    ["order", "sipariş"],
    ["author", "yazar"],
    ["fill", "doldurmak"],
    ["represent", "temsil etmek"],
    ["focus", "odaklanmak"],
    ["foreign", "yabancı"],
    ["drop", "düşürmek"],
    ["blood", "kan"],
    ["upon", "üzerine"],
    ["agency", "ajans"],
    ["push", "itmek"],
    ["nature", "doğa"],
    ["color", "renk"],
    ["no", "hayır"],
    ["recently", "son zamanlarda"],
    ["store", "mağaza"],
    ["reduce", "azaltmak"],
    ["sound", "ses"],
    ["note", "not"],
    ["fine", "iyi"],
    ["before", "önce"],
    ["near", "yakın"],
    ["movement", "hareket"],
    ["page", "sayfa"],
    ["enter", "girmek"],
    ["share", "paylaşmak"],
    ["than", "den daha"],
    ["common", "ortak"],
    ["poor", "fakir"],
    ["other", "diğer"],
    ["natural", "doğal"],
    ["race", "yarış"],
    ["concern", "endişe"],
    ["series", "dizi"],
    ["significant", "önemli"],
    ["similar", "benzer"],
    ["hot", "sıcak"],
    ["language", "dil"],
    ["each", "her biri"],
    ["usually", "genellikle"],
    ["response", "tepki"],
    ["dead", "ölü"],
    ["rise", "yükselmek"],
    ["animal", "hayvan"],
    ["factor", "faktör"],
    ["decade", "on yıl"],
    ["article", "makale"],
    ["shoot", "vurmak"],
    ["east", "doğu"],
    ["save", "kaydetmek"],
    ["seven", "yedi"],
    ["artist", "sanatçı"],
    ["scene", "sahne"],
    ["stock", "stok"],
    ["career", "kariyer"],
    ["despite", "rağmen"],
    ["central", "merkezi"],
    ["eight", "sekiz"],
    ["thus", "böylece"],
    ["treatment", "tedavi"],
    ["beyond", "ötesinde"],
    ["happy", "mutlu"],
    ["exactly", "tam olarak"],
    ["protect", "korumak"],
    ["approach", "yaklaşım"],
    ["lie", "yalan"],
    ["size", "boyut"],
    ["dog", "köpek"],
    ["fund", "fon"],
    ["serious", "ciddi"],
    ["occur", "meydana gelmek"],
    ["media", "medya"],
    ["ready", "hazır"],
    ["sign", "işaret"],
    ["thought", "düşünce"],
    ["list", "liste"],
    ["individual", "birey"],
    ["simple", "basit"],
    ["quality", "kalite"],
    ["pressure", "baskı"],
    ["accept", "kabul etmek"],
    ["answer", "cevap"],
    ["resource", "kaynak"],
    ["identify", "tanımlamak"],
    ["left", "sol"],
    ["meeting", "toplantı"],
    ["determine", "belirlemek"],
    ["prepare", "hazırlamak"],
    ["disease", "hastalık"],
    ["whatever", "her neyse"],
    ["success", "başarı"],
    ["argue", "tartışmak"],
    ["cup", "fincan"],
    ["particularly", "özellikle"],
    ["amount", "miktar"],
    ["ability", "yetenek"],
    ["staff", "personel"],
    ["recognize", "tanımak"],
    ["indicate", "göstermek"],
    ["character", "karakter"],
    ["growth", "büyüme"],
    ["loss", "kayıp"],
    ["degree", "derece"],
    ["wonder", "merak etmek"],
    ["attack", "saldırı"],
    ["herself", "kendisi"],
    ["region", "bölge"],
    ["television", "televizyon"],
    ["box", "kutu"],
    ["TV", "televizyon"],
    ["training", "eğitim"],
    ["pretty", "oldukça"],
    ["trade", "ticaret"],
    ["deal", "anlaşmak"],
    ["election", "seçim"],
    ["everybody", "herkes"],
    ["physical", "fiziksel"],
    ["lay", "koymak"],
    ["general", "genel"],
    ["feeling", "hissetme"],
    ["standard", "standart"],
    ["bill", "fatura"],
    ["message", "mesaj"],
    ["fail", "başarısız olmak"],
    ["outside", "dışarıda"],
    ["arrive", "varmak"],
    ["analysis", "analiz"],
    ["benefit", "fayda"],
    ["name", "ad"],

    ["forward", "ileri"],
    ["lawyer", "avukat"],
    ["present", "sunmak"],
    ["section", "bölüm"],
    ["environmental", "çevresel"],
    ["glass", "cam"],
    ["answer", "yanıt"],
    ["skill", "beceri"],
    ["sister", "kız kardeş"],
    ["PM", "ÖS"],
    ["professor", "profesör"],
    ["operation", "operasyon"],
    ["financial", "finansal"],
    ["crime", "suç"],
    ["stage", "sahne"],
    ["compare", "karşılaştırmak"],
    ["authority", "yetki"],
    ["miss", "kaçırmak"],
    ["design", "tasarım"],
    ["sort", "sıralamak"],
    ["one", "bir"],
    ["act", "hareket etmek"],
    ["ten", "on"],
    ["knowledge", "bilgi"],
    ["gun", "silah"],
    ["station", "istasyon"],
    ["blue", "mavi"],
    ["state", "durum"],
    ["strategy", "strateji"],
    ["little", "az"],
    ["clearly", "açıkça"],
    ["discuss", "tartışmak"],
    ["indeed", "gerçekten"],
    ["force", "kuvvet"],
    ["truth", "gerçek"],
    ["song", "şarkı"],
    ["example", "örnek"],
    ["democratic", "demokratik"],
    ["check", "kontrol etmek"],
    ["environment", "çevre"],
    ["leg", "bacak"],
    ["dark", "karanlık"],
    ["public", "halk"],
    ["various", "çeşitli"],
    ["rather", "oldukça"],
    ["laugh", "gülmek"],
    ["guess", "tahmin etmek"],
    ["executive", "yürütme"],
    ["set", "ayarlamak"],
    ["study", "çalışma"],
    ["prove", "kanıtlamak"],
    ["hang", "asmak"],
    ["entire", "tüm"],
    ["rock", "kaya"],
    ["design", "tasarlamak"],
    ["enough", "yeterli"],
    ["forget", "unutmak"],
    ["since", "beri"],
    ["claim", "iddia etmek"],
    ["note", "not"],
    ["remove", "kaldırmak"],
    ["manager", "yönetici"],
    ["help", "yardım"],
    ["close", "yakın"],
    ["sound", "ses"],
    ["enjoy", "hoşlanmak"],
    ["network", "ağ"],
    ["legal", "yasal"],
    ["religious", "dini"],
    ["cold", "soğuk"],
    ["form", "form"],
    ["final", "son"],
    ["main", "ana"],
    ["science", "bilim"],
    ["green", "yeşil"],
    ["memory", "hafıza"],
    ["card", "kart"],
    ["above", "yukarıda"],
    ["seat", "koltuk"],
    ["cell", "hücre"],
    ["establish", "kurmak"],
    ["nice", "güzel"],
    ["trial", "deneme"],
    ["expert", "uzman"],
    ["that", "şu"],
    ["spring", "ilkbahar"],
    ["firm", "firma"],
    ["Democrat", "Demokrat"],
    ["radio", "radyo"],
    ["visit", "ziyaret"],
    ["management", "yönetim"],
    ["care", "ilgi"],
    ["avoid", "kaçınmak"],
    ["imagine", "hayal etmek"],
    ["tonight", "bu gece"],
    ["huge", "büyük"],
    ["ball", "top"],
    ["no", "hiç"],
    ["close", "kapatmak"],
    ["finish", "bitirmek"],
    ["yourself", "kendin"],
    ["talk", "konuşma"],
    ["theory", "teori"],
    ["impact", "etki"],
    ["respond", "yanıt vermek"],
    ["statement", "açıklama"],
    ["maintain", "sürdürmek"],
    ["charge", "şarj"],
    ["popular", "popüler"],
    ["traditional", "geleneksel"],
    ["onto", "üzerine"],
    ["reveal", "açığa çıkarmak"],
    ["direction", "yön"],
    ["weapon", "silah"],
    ["employee", "çalışan"],
    ["cultural", "kültürel"],
    ["contain", "içermek"],
    ["peace", "barış"],
    ["head", "baş"],
    ["control", "kontrol"],
    ["base", "taban"],
    ["pain", "acı"],
    ["apply", "uygulamak"],
    ["play", "oynamak"],
    ["measure", "ölçmek"],
    ["wide", "geniş"],
    ["shake", "sallamak"],
    ["fly", "uçmak"],
    ["interview", "görüşme"],
    ["manage", "yönetmek"],
    ["chair", "sandalye"],
    ["fish", "balık"],
    ["particular", "belirli"],
    ["camera", "kamera"],
    ["structure", "yapı"],
    ["politics", "siyaset"],
    ["perform", "gerçekleştirmek"],
    ["bit", "biraz"],
    ["weight", "ağırlık"],
    ["suddenly", "aniden"],
    ["discover", "keşfetmek"],
    ["candidate", "aday"],
    ["top", "üst"],
    ["production", "üretim"],
    ["treat", "tedavi etmek"],
    ["trip", "gezi"],
    ["evening", "akşam"],
    ["affect", "etkilemek"],
    ["inside", "içeride"],
    ["conference", "konferans"],
    ["unit", "birim"],
    ["best", "en iyi"],
    ["style", "stil"],
    ["adult", "yetişkin"],
    ["worry", "endişelenmek"],
    ["range", "aralık"],
    ["mention", "bahsetmek"],
    ["rather", "tercihen"],
    ["far", "uzak"],
    ["deep", "derin"],
    ["past", "geçmiş"],
    ["edge", "kenar"],
    ["individual", "birey"],
    ["specific", "belirli"],
    ["writer", "yazar"],
    ["trouble", "sorun"],
    ["necessary", "gereken"],
    ["throughout", "boyunca"],
    ["challenge", "meydan okuma"],
    ["fear", "korku"],
    ["shoulder", "omuz"],
    ["institution", "kurum"],
    ["middle", "orta"],
    ["sea", "deniz"],
    ["dream", "hayal"],
    ["bar", "bar"],
    ["beautiful", "güzel"],
    ["property", "mülk"],
    ["instead", "yerine"],
    ["improve", "iyileştirmek"],
    ["stuff", "şeyler"],
    ["detail", "detay"],
    ["method", "yöntem"],
    ["sign", "işaret"],
    ["somebody", "birisi"],
    ["magazine", "dergi"],
    ["hotel", "otel"],
    ["soldier", "asker"],
    ["reflect", "yansıtmak"],
    ["heavy", "ağır"],

    ["bag", "çanta"],
    ["heat", "ısı"],
    ["marriage", "evlilik"],
    ["tough", "zor"],
    ["sing", "söylemek"],
    ["surface", "yüzey"],
    ["purpose", "amaç"],
    ["exist", "var olmak"],
    ["pattern", "desen"],
    ["whom", "kimi"],
    ["skin", "cilt"],
    ["agent", "ajan"],
    ["owner", "sahip"],
    ["machine", "makine"],
    ["gas", "gaz"],
    ["down", "aşağı"],
    ["ahead", "önünde"],
    ["generation", "nesil"],
    ["commercial", "ticari"],
    ["address", "adres"],
    ["cancer", "kanser"],
    ["test", "test"],
    ["item", "madde"],
    ["reality", "gerçeklik"],
    ["coach", "antrenör"],
    ["step", "adım"],
    ["Mrs", "Bayan"],
    ["yard", "avlu"],
    ["beat", "vurmak"],
    ["violence", "şiddet"],
    ["total", "toplam"],
    ["tend", "eğilimli olmak"],
    ["investment", "yatırım"],
    ["discussion", "tartışma"],
    ["finger", "parmak"],
    ["garden", "bahçe"],
    ["notice", "fark etmek"],
    ["collection", "koleksiyon"],
    ["modern", "modern"],
    ["task", "görev"],
    ["partner", "ortak"],
    ["positive", "olumlu"],
    ["civil", "sivil"],
    ["kitchen", "mutfak"],
    ["consumer", "tüketici"],
    ["shot", "ateş"],
    ["budget", "bütçe"],
    ["wish", "dilemek"],
    ["painting", "resim"],
    ["scientist", "bilim adamı"],
    ["safe", "güvenli"],
    ["agreement", "anlaşma"],
    ["capital", "başkent"],
    ["mouth", "ağız"],
    ["nor", "ne de"],
    ["victim", "kurban"],
    ["newspaper", "gazete"],
    ["threat", "tehdit"],
    ["responsibility", "sorumluluk"],
    ["smile", "gülümsemek"],
    ["attorney", "avukat"],
    ["score", "puan"],
    ["account", "hesap"],
    ["interesting", "ilginç"],
    ["break", "mola"],
    ["audience", "seyirci"],
    ["rich", "zengin"],
    ["dinner", "akşam yemeği"],
    ["figure", "şekil"],
    ["vote", "oy"],
    ["western", "batı"],
    ["relate", "ilişkilendirmek"],
    ["travel", "seyahat"],
    ["debate", "tartışma"],
    ["prevent", "önlemek"],
    ["citizen", "vatandaş"],
    ["majority", "çoğunluk"],
    ["none", "hiçbiri"],
    ["front", "ön"],
    ["born", "doğmak"],
    ["admit", "itiraf etmek"],
    ["senior", "üst"],
    ["assume", "varsaymak"],
    ["wind", "rüzgar"],
    ["key", "anahtar"],
    ["professional", "profesyonel"],
    ["mission", "görev"],
    ["fast", "hızlı"],
    ["alone", "yalnız"],
    ["customer", "müşteri"],
    ["suffer", "acı çekmek"],
    ["speech", "konuşma"],
    ["successful", "başarılı"],
    ["option", "seçenek"],
    ["participant", "katılımcı"],
    ["southern", "güney"],
    ["fresh", "taze"],
    ["eventually", "sonunda"],
    ["forest", "orman"],
    ["video", "video"],
    ["global", "küresel"],
    ["Senate", "Senato"],
    ["reform", "reform"],
    ["access", "erişim"],
    ["restaurant", "restoran"],
    ["judge", "hakim"],
    ["publish", "yayımlamak"],
    ["cost", "maliyet"],
    ["relation", "ilişki"],
    ["like", "gibi"],
    ["release", "serbest bırakmak"],
    ["own", "sahip olmak"],
    ["bird", "kuş"],
    ["opinion", "görüş"],
    ["credit", "kredi"],
    ["critical", "kritik"],
    ["corner", "köşe"],
    ["concerned", "endişeli"],
    ["recall", "hatırlamak"],
    ["version", "sürüm"],
    ["stare", "dik dik bakmak"],
    ["safety", "güvenlik"],
    ["effective", "etkili"],
    ["neighborhood", "mahalle"],
    ["original", "orijinal"],
    ["actress", "aktris"],
    ["troop", "birlik"],
    ["income", "gelir"],
    ["directly", "doğrudan"],
    ["hurt", "hasta"],
    ["species", "tür"],
    ["immediately", "hemen"],
    ["track", "iz"],
    ["basic", "temel"],
    ["strike", "vurmak"],
    ["sky", "gökyüzü"],
    ["freedom", "özgürlük"],
  ];
  storedWords = defaultWords;
  storedWords = JSON.stringify(storedWords);
  localStorage.setItem("words", storedWords);
  storedWords = JSON.parse(storedWords);
}
let add = false;
const wordsDiv = document.getElementsByClassName("words")[0];

const sil = (i) => {
  storedWords.splice(i, 1);
  getStorage(storedWords);
  localStorage.setItem("words", JSON.stringify(storedWords));
};

const getStorage = (storedWords) => {
  wordsDiv.innerHTML = "";
  const fragment = document.createDocumentFragment();
  storedWords?.forEach((item, i) => {
    const listItem = document.createElement("li");
    listItem.classList.add("word");
    listItem.innerHTML = `${item[0]} <span class="versus"> - </span> ${item[1]}`;
    const deleteButton = document.createElement("div");
    deleteButton.classList.add("delete");
    deleteButton.setAttribute("onClick", `sil(${i})`);
    deleteButton.setAttribute("title", "Sil");
    deleteButton.textContent = "x";
    listItem.appendChild(deleteButton);
    fragment.appendChild(listItem);
  });
  wordsDiv.appendChild(fragment);
};

getStorage(storedWords);

const addStorage = (e) => {
  let turkish = document.getElementsByName("turkish")[0].value;
  let english = document.getElementsByName("english")[0].value;
  document.getElementsByName("turkish")[0].value = "";
  document.getElementsByName("english")[0].value = "";
  const newWords = [english, turkish];
  if (storedWords) storedWords.push(newWords);
  else storedWords = [newWords];
  storedWords = JSON.stringify(storedWords);
  localStorage.setItem("words", storedWords);
  storedWords = JSON.parse(storedWords);
  getStorage(storedWords);
};

let getAdd = document.getElementsByClassName("getAdd")[0];
let addPage = document.getElementsByClassName("addPage")[0];

getAdd.addEventListener("click", () => {
  let addPageInner = `<div class="fullPage">
    <span onClick="toggle()" class="versus" style="position:absolute;top:0;right:0" title="Kapat">X</span>
    <div style="margin-bottom:10px">Kelime Ekle</div>
  <div class="languages">
    <div  >İngilizce</div>
    <div class="versus">-</div>
    <div  >Türkçe</div>
</div>
<div class="inputs">
    <input type="text" name="english"><span class="versus">-</span>
    <input type="text" name="turkish">
    
</div>
<button class="addBtn" onClick=addStorage()>Ekle</button>
</div>`;

  if (!add) {
    addPage.innerHTML = addPageInner;
    add = !add;
  } else {
    addPage.innerHTML = "";
    add = !add;
  }
});

function toggle() {
  addPage.innerHTML = "";
  add = !add;
}

document.onkeydown = function (evt) {
  evt = evt || window.event;
  var isEscape = false;
  if ("key" in evt) {
    isEscape = evt.key === "Escape" || evt.key === "Esc";
  } else {
    isEscape = evt.keyCode === 27;
  }
  if (isEscape) {
    if (add) {
      addPage.innerHTML = "";
      add = !add;
    }
  }
};

document.addEventListener("click", (e) => {
  let fullPageBox = document.querySelectorAll(".fullPage")[0];
  let addBox = document.querySelectorAll(".getAdd")[0];

  if (
    !e.composedPath().includes(fullPageBox) &&
    !e.composedPath().includes(addBox)
  ) {
    if (add) {
      addPage.innerHTML = "";
      add = !add;
    }
  }
});
